version: '2.1'

services:

  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env