version: '2.1'

services:

  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  celery:
    build: .
    command: ["/code/run_celery.sh"]
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - web
    ports:
      - "5555:5555"
    env_file:
      - .env