# Generated by Django 3.2.9 on 2022-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='page.Page'),
        ),
    ]
