# Generated by Django 3.2.9 on 2022-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
