# Generated by Django 3.2.9 on 2022-02-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_page_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
