# Generated by Django 3.2.9 on 2022-02-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image_s3_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_s3_path',
            new_name='avatar',
        ),
    ]
